In [1]:
import os

def list_files(startpath):
    for root, dirs, files in os.walk(startpath):
        level = root.replace(startpath, '').count(os.sep)
        indent = ' ' * 4 * (level)
        print('{}{}/'.format(indent, os.path.basename(root)))
        subindent = ' ' * 4 * (level + 1)
        for f in files:
            print('{}{}'.format(subindent, f))
list_files("../")

/
    0-运行说明.txt
    1-模型说明.txt
    学生证.jpg
cache/
    code2_weighted_edglist_DeepWalk.txt
    code2_weighted_edglist_filytypeTxt.edgelist
    code2_weighted_edglist_filytypeTxt.txt
    device1_edglist_emb_dim36.emb
    device1_weighted_edglist_DeepWalk.txt
    device1_weighted_edglist_filytypeTxt.edgelist
    device1_weighted_edglist_filytypeTxt.txt
    device_code1_weighted_edglist_DeepWalk.txt
    device_code1_weighted_edglist_filytypeTxt.edgelist
    device_code1_weighted_edglist_filytypeTxt.txt
    device_code2_edglist_emb_dim36.emb
    device_code2_weighted_edglist_DeepWalk.txt
    device_code2_weighted_edglist_filytypeTxt.edgelist
    device_code2_weighted_edglist_filytypeTxt.txt
    device_code3_weighted_edglist_DeepWalk.txt
    device_code3_weighted_edglist_filytypeTxt.edgelist
    device_code3_weighted_edglist_filytypeTxt.txt
    geo_code_edglist.embeddings
    geo_code_edglist_emb_dim36.emb
    geo_code_weighted_edglist_DeepWalk.txt
    geo_code_weighted_edglist_filytypeTxt.

In [ ]:
%run 1-0-data_preprocess.ipynb
%run 1-1-EdgePrepare.ipynb
%run 1-2-Graph_embeddings.ipynb
%run 2-1-FeatureExact.ipynb
%run 2-2-extract_features.ipynb
%run 3-1-lgb_embedding.ipynb
%run 3-2-lightgbm_model.ipynb
%run 4-1-blend_model.ipynb
%run 4-2-rule_adjust.ipynb

In [4]:
# import pandas as pd
df = pd.read_csv("../cache/2018-12-16_737044/device1__embtype_emb_test_0_.csv")
df1 = pd.read_csv("../cache/2018-12-16_737044/device_code2__embtype_emb_test_1_.csv")

In [31]:
import numpy as np

a = np.zeros(df.shape[0])
b = np.zeros(df.shape[0])

In [33]:
a[df.index] = df.Tag.values
b[df1.index] = df1.Tag.values

In [38]:
df.Tag.values,df1.Tag.values

(array([0.23221805, 0.15608086, 0.18109191, ..., 0.33726053, 0.2386923 ,
        0.0899235 ]),
 array([0.22765584, 0.1648382 , 0.16894631, ..., 0.33768669, 0.25256878,
        0.07470897]))

In [40]:
np.concatenate( [df.Tag.values.reshape(-1,1),df1.Tag.values.reshape(-1,1)  ] ,axis=1) 

array([[0.23221805, 0.22765584],
       [0.15608086, 0.1648382 ],
       [0.18109191, 0.16894631],
       ...,
       [0.33726053, 0.33768669],
       [0.2386923 , 0.25256878],
       [0.0899235 , 0.07470897]])

In [41]:
df.Tag.values.reshape(-1,1)

array([[0.23221805],
       [0.15608086],
       [0.18109191],
       ...,
       [0.33726053],
       [0.2386923 ],
       [0.0899235 ]])

In [45]:
y_train.ravel()

array([1, 0, 0, ..., 0, 1, 1], dtype=int64)

In [44]:
len(y_train)

31179